### ISSUE TITLE
Licensing issue.

### ISSUE THREAD

**Issue by mfilippov** [jnm2/ReferenceAssemblies.net35#1]
What do you think about the licensing issue? You extracted reference assemblies from OS with installed Visual Studio and you have MIT license on NuGet package. I'm not sure about MIT license availability for this DLL's. Have you any permissions to do it from Microsoft? We want to make .NET 3.5 reference assemblies too but we can't find the right way to do it now.

**Comment by jnm2** [comment]
Thanks for the question. I was careful to make sure that the entirety of this repository is MIT-licensed. I wrote all the code from scratch except for the .targets file which is based on a NuGet package that has an MIT license (see the link within the file). You can build the package from source yourself by running [`build.cmd`](https://github.com/jnm2/ReferenceAssemblies.net35/blob/master/build.cmd) using your own installation of the .NET 3.5 reference assemblies.

So much for the GitHub repo itself. As for the generated NuGet package, I chose MIT because that is what Microsoft used in https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies.net20, and many of the same .NET 2.0 assemblies are unchanged in 3.5. For the few remaining assemblies, I'm not sure what the redistribution license is. I'll try to get an answer for you.

**Comment by jnm2** [comment]
@mfilippov This is what I found out:

- A portion of the binaries in the package I redistributed are not redistributable, while others (the ones duplicated in the 2.0 package) are MIT.

- The .NET team has no path in place for granting redistribution rights for the non-MIT ones.

- If this became a problem for any reason, I can simply take the MIT-licensed 4.0 assemblies and trim the API down to match the 3.5 API shape. The result would be identical to what I published already except that the strong-naming public key token and the Authenticode signatures would be lost. Authenticode doesn't matter for this, and I can use public signing to reapply Microsoft's public key token to the reference assemblies so that the correct public key token is encoded in assemblies compiled against them.

I'd prefer not to do the extra work until asked. The motivation for asking is unclear to me; if asked, the resolution would be that I publish a new package that is identical to the current one for all intents and purposes.

What is the specific reason that you are interested? Are you thinking of redistributing this NuGet package, or merely building against it which does not involve redistribution?

**Comment by mfilippov** [comment]
@jnm2 Thank you for your answer. I want to use your package to build our products on CI it is the reason for my question. I need to be sure that I won't have any legal issues after that. I spent little time to check your package and I see some assemblies has a body an example System.WorkflowServices.dll WindowBase.dll etc... I think it violates the .NET Framework license.

**Comment by jnm2** [comment]
I'm going to be publishing a 1.0.1 soon and would like to look at solving this issue for you first.

**Comment by jnm2** [comment]
Corrections:

- The API may be the same between many of the net20 and net35 assemblies, but the files are not identical.

- These files do not exist in net20 *or* net40, so they will have to be removed unless another redistributable source is available besides the Microsoft.NETFramework.ReferenceAssemblies packages:
  - Microsoft.Build.Conversion.v3.5
  - Microsoft.Build.Utilities.v3.5
  - Microsoft.Build.Tasks.v3.5
  - Microsoft.Data.Entity.Build.Tasks
  - Sentinel.v3.5Client

- These files exist in net20 and net35 but not net40. If the API is for any of these doesn't happen to be the same as the net20 version, it will also have to be removed for the same reason as the previous point:
  - AspNetMMCExt
  - cscompmgd
  - IEExecRemote
  - IEHost
  - IIEHost
  - Microsoft.Build.Tasks
  - Microsoft.Build.Utilities
  - Microsoft.VisualBasic.Vsa
  - Microsoft.Vsa
  - Microsoft.Vsa.Vb.CodeDOMProcessor
  - Microsoft_VsaVb

**Comment by jnm2** [comment]
An approach I didn't think of before would be to actually build brand new net35 reference assemblies from source using https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/refonly-compiler-option. The APIs could then be checked for equivalence against the non-distributable assemblies.

**Comment by jnm2** [comment]
https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies.net35 has been published and is included in https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies, so this package is now obsolete in the best way.
