### ISSUE TITLE
Where is the authenticode signature?

### ISSUE THREAD

**Issue by AArnott** [jnm2/ReferenceAssemblies.net35#5]
net20 and net40 assemblies are authenticode signed when found in the `microsoft.netframework.referenceassemblies` packages. Why aren't the same dll's authenticode signed as found in your package?

**Comment by jnm2** [comment]
I wasn't aware of that. The DLLs in this package are the reference assemblies the compiler provides to csc.exe when you compile a `net35` project. Perhaps an additional Authenticode signing step was performed on the assemblies in the Microsoft.NetFramework.ReferenceAssemblies packages?

Since these are actually the exact same assemblies you get when you compile a net35 project, what would the reason be to add Authenticode signing to my package? To achieve that, we would either have to find a second source for .NET Framework 3.5 reference assemblies that is already signed, or I could look into getting myself an authenticode signing certificate.

**Comment by AArnott** [comment]
It's a trust thing. All the other assemblies are authenticode signed *by Microsoft* but the ones found in your package are not. You signing them wouldn't address the problem.

You may be right: maybe MS didn't sign them originally and only signed the ones they published to nuget.org. I'll do some more research.

**Comment by AArnott** [comment]
The strong name signatures appear to be intact, so that's good.

**Comment by jnm2** [comment]
Also, I have something in the works. I might flip a switch sometime soon and be building these assemblies from generated minimal API-declaring source using `csc.exe /refonly`. If Authenticode provides a real benefit, I'd definitely need to first get my own certificate. There's no way you'd expect them to be signed by Microsoft.
(I'm public-signing them with the original public key, so the strong name identity will not change, but the .NET Framework runtime will refuse to load these assemblies for execution. That's okay because reference assemblies should not be loaded for execution.)

The trust question has two parts that I can think of right now:
- Is this going to produce identical compile output in every situation when I use this for my csc.exe references?
- Does the package contain malware?

For the first question, I'll have a metadata-level tool that lists any difference in the metadata of the official reference assemblies from the metadata of the true ref assemblies that I generate. I might use Microsoft's own API compat tool for this.

For the second question, I think NuGet.org checks for malware.

**Comment by AArnott** [comment]
Your ref assembly idea is good as far as shrinking the package, but since you're redist'ing MS files, IMO keeping any signatures MS has on them seems more valuable.
I confirmed what you're saying: the original ref assemblies MS shipped in the SDK are not authenticode signed.

**Comment by jnm2** [comment]
> Your ref assembly idea is good as far as shrinking the package, but since you're redist'ing MS files, IMO keeping any signatures MS has on them seems more valuable.

https://github.com/jnm2/ReferenceAssemblies.net35/issues/1 is the main reason why I have this second option close to being ready. (I also plan to use the tool on unrelated third party platform assemblies, and in that case I have a strong motivation to shrink them.) Otherwise, yes, I'd consider this package to be in its final form.

**Comment by jnm2** [comment]
If there's too much conflict between what you're asking for and what #1 is asking for, perhaps that necessitates a separate package and maybe a fork since I'd rather not store any binaries in my repo. I've already gotten so close with storing the API definitions as source and compiling true ref assemblies to close #1 that I do have a desire to go ahead with that. On the other hand, even https://github.com/dotnet/msbuild is using https://www.nuget.org/packages/jnm2.ReferenceAssemblies.net35, so maybe I should keep things as-is for now.

**Comment by AArnott** [comment]
> On the other hand, even https://github.com/dotnet/msbuild is using https://www.nuget.org/packages/jnm2.ReferenceAssemblies.net35, so maybe I should keep things as-is for now.

[Oh wow](https://github.com/dotnet/msbuild/blob/6819f7ab06c3f43e83ff4059d417395e0af06c01/eng/Packages.props#L4). That definitely adds some credibility. :) That, and the author's name (yours) helped too.

**Comment by jnm2** [comment]
I'm going to close since you confirmed that me adding my own Authenticode signature is not what you want, and we don't know of the existence of Authenticode-signed reference assemblies for .NET Framework 3.5. If either of those things changes, let's reopen.

Also, if you can quantify trust and credibility and have an idea of an alternative strategy that would move the needle for you, let's open a separate issue focused on that.

**Comment by jnm2** [comment]
https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies.net35 has been published and is included in https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies, so this package is now obsolete in the best way.
